# Generated by Django 5.1.7 on 2025-04-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_organizer_alter_event_name_alter_event_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
