# Generated by Django 5.1.7 on 2025-04-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendee_count',
            field=models.IntegerField(default=0),
        ),
    ]
