# Generated by Django 5.1.7 on 2025-04-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_creator_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='moderation',
            field=models.BooleanField(default=False),
        ),
    ]
