# Generated by Django 5.1.7 on 2025-04-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_creator_alter_event_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
